//Used to do early testing

//import firebase from '@/firebase/initFirebase';

//I want a piece of information that can be shared by multiple instances, hence the vue state
export const store = {
    state: {
        currentUser: null,
        showMenu: false,
        showSignOut: false,
        rounds: [
            1.1,
            1.2,
            1.3,
            1.4,
            2.1,
            2.2,
            2.3,
            2.4,
            2.5,
            2.6,
            2.7,
            3.1,
            3.2,
            3.3,
            3.4,
            3.5,
            3.6,
            3.7,
            4.1,
            4.2,
            4.3,
            4.4,
            4.5,
            4.6,
            4.7,
            5.1,
            5.2,
            5.3,
            5.4,
            5.5,
            5.6,
            5.7,
            6.1,
            6.2,
            6.3,
            6.4,
            6.5,
            6.6,
            6.7,
            7.1,
            7.2,
            7.3,
            7.4,
            7.5,
            7.6,
            7.7
        ],
        roundsType: [
            "Carousel",
            "Minions",
            "Minions",
            "Minions",
            "Battle",
            "Battle",
            "Battle",
            "Carousel",
            "Battle",
            "Battle",
            "Krugs",
            "Battle",
            "Battle",
            "Battle",
            "Carousel",
            "Battle",
            "Battle",
            "Wolves",
            "Battle",
            "Battle",
            "Battle",
            "Carousel",
            "Battle",
            "Battle",
            "Raptors",
            "Battle",
            "Battle",
            "Battle",
            "Carousel",
            "Battle",
            "Battle",
            "Dragon",
            "Battle",
            "Battle",
            "Battle",
            "Carousel",
            "Battle",
            "Battle",
            "Rift Herald OR Elder Dragon",
            "Battle",
            "Battle",
            "Battle",
            "Carousel",
            "Battle",
            "Battle",
            "Elder Dragon"
        ]
    }
}; 
